/* jni_unimpl.h -- GENERATED by the block in this comment; do not hand-edit.
 *
 * One stub per JNIEnv slot, each logging its own index, replacing a single
 * shared j_unimplemented() that returned 0 in silence.
 *
 * Adapted from fruitninja_nx, whose version does the same thing. Returning 0
 * quietly is the same silent-promise pattern as the stdio writers and
 * android_set_abort_message: the caller takes 0 for a real answer -- a null
 * jobject, a zero jfieldID, an empty array -- and carries on building
 * something half-initialised. That is exactly the shape of object the repeating
 * crash walks: a valid vtable, valid neighbours, and one field holding a small
 * integer where a pointer belongs.
 *
 * Each slot logs ONCE. A JNI call in a hot path would otherwise bury the log,
 * and the second occurrence tells us nothing the first did not.
 *
 * Names come from the JNI 1.6 specification's function-table order. Only ones
 * that could be stated with confidence are included; the rest print the index
 * alone, because a wrong name in a diagnostic is worse than no name.
 */
#ifndef __JNI_UNIMPL_H__
#define __JNI_UNIMPL_H__

#include "util.h"   // debugPrintf; declared here once, not per-header

#include <stdint.h>


static const char *ju_name(int slot);
static unsigned char ju_seen[256];

static uint64_t ju_log(int slot) {
  if (!ju_seen[slot]) {
    ju_seen[slot] = 1;
    const char *n = ju_name(slot);
    debugPrintf("[jni] UNIMPLEMENTED slot %d%s%s%s -- returning 0, which the "
                "caller will treat as a real answer\n",
                slot, n ? " (" : "", n ? n : "", n ? ")" : "");
    debugFlush();
  }
  return 0;
}

static uint64_t ju_0(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(0);}
static uint64_t ju_1(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(1);}
static uint64_t ju_2(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(2);}
static uint64_t ju_3(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(3);}
static uint64_t ju_4(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(4);}
static uint64_t ju_5(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(5);}
static uint64_t ju_6(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(6);}
static uint64_t ju_7(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(7);}
static uint64_t ju_8(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(8);}
static uint64_t ju_9(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(9);}
static uint64_t ju_10(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(10);}
static uint64_t ju_11(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(11);}
static uint64_t ju_12(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(12);}
static uint64_t ju_13(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(13);}
static uint64_t ju_14(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(14);}
static uint64_t ju_15(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(15);}
static uint64_t ju_16(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(16);}
static uint64_t ju_17(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(17);}
static uint64_t ju_18(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(18);}
static uint64_t ju_19(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(19);}
static uint64_t ju_20(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(20);}
static uint64_t ju_21(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(21);}
static uint64_t ju_22(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(22);}
static uint64_t ju_23(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(23);}
static uint64_t ju_24(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(24);}
static uint64_t ju_25(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(25);}
static uint64_t ju_26(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(26);}
static uint64_t ju_27(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(27);}
static uint64_t ju_28(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(28);}
static uint64_t ju_29(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(29);}
static uint64_t ju_30(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(30);}
static uint64_t ju_31(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(31);}
static uint64_t ju_32(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(32);}
static uint64_t ju_33(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(33);}
static uint64_t ju_34(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(34);}
static uint64_t ju_35(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(35);}
static uint64_t ju_36(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(36);}
static uint64_t ju_37(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(37);}
static uint64_t ju_38(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(38);}
static uint64_t ju_39(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(39);}
static uint64_t ju_40(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(40);}
static uint64_t ju_41(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(41);}
static uint64_t ju_42(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(42);}
static uint64_t ju_43(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(43);}
static uint64_t ju_44(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(44);}
static uint64_t ju_45(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(45);}
static uint64_t ju_46(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(46);}
static uint64_t ju_47(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(47);}
static uint64_t ju_48(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(48);}
static uint64_t ju_49(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(49);}
static uint64_t ju_50(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(50);}
static uint64_t ju_51(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(51);}
static uint64_t ju_52(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(52);}
static uint64_t ju_53(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(53);}
static uint64_t ju_54(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(54);}
static uint64_t ju_55(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(55);}
static uint64_t ju_56(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(56);}
static uint64_t ju_57(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(57);}
static uint64_t ju_58(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(58);}
static uint64_t ju_59(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(59);}
static uint64_t ju_60(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(60);}
static uint64_t ju_61(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(61);}
static uint64_t ju_62(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(62);}
static uint64_t ju_63(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(63);}
static uint64_t ju_64(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(64);}
static uint64_t ju_65(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(65);}
static uint64_t ju_66(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(66);}
static uint64_t ju_67(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(67);}
static uint64_t ju_68(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(68);}
static uint64_t ju_69(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(69);}
static uint64_t ju_70(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(70);}
static uint64_t ju_71(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(71);}
static uint64_t ju_72(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(72);}
static uint64_t ju_73(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(73);}
static uint64_t ju_74(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(74);}
static uint64_t ju_75(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(75);}
static uint64_t ju_76(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(76);}
static uint64_t ju_77(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(77);}
static uint64_t ju_78(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(78);}
static uint64_t ju_79(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(79);}
static uint64_t ju_80(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(80);}
static uint64_t ju_81(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(81);}
static uint64_t ju_82(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(82);}
static uint64_t ju_83(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(83);}
static uint64_t ju_84(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(84);}
static uint64_t ju_85(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(85);}
static uint64_t ju_86(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(86);}
static uint64_t ju_87(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(87);}
static uint64_t ju_88(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(88);}
static uint64_t ju_89(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(89);}
static uint64_t ju_90(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(90);}
static uint64_t ju_91(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(91);}
static uint64_t ju_92(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(92);}
static uint64_t ju_93(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(93);}
static uint64_t ju_94(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(94);}
static uint64_t ju_95(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(95);}
static uint64_t ju_96(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(96);}
static uint64_t ju_97(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(97);}
static uint64_t ju_98(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(98);}
static uint64_t ju_99(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(99);}
static uint64_t ju_100(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(100);}
static uint64_t ju_101(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(101);}
static uint64_t ju_102(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(102);}
static uint64_t ju_103(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(103);}
static uint64_t ju_104(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(104);}
static uint64_t ju_105(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(105);}
static uint64_t ju_106(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(106);}
static uint64_t ju_107(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(107);}
static uint64_t ju_108(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(108);}
static uint64_t ju_109(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(109);}
static uint64_t ju_110(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(110);}
static uint64_t ju_111(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(111);}
static uint64_t ju_112(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(112);}
static uint64_t ju_113(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(113);}
static uint64_t ju_114(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(114);}
static uint64_t ju_115(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(115);}
static uint64_t ju_116(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(116);}
static uint64_t ju_117(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(117);}
static uint64_t ju_118(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(118);}
static uint64_t ju_119(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(119);}
static uint64_t ju_120(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(120);}
static uint64_t ju_121(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(121);}
static uint64_t ju_122(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(122);}
static uint64_t ju_123(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(123);}
static uint64_t ju_124(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(124);}
static uint64_t ju_125(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(125);}
static uint64_t ju_126(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(126);}
static uint64_t ju_127(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(127);}
static uint64_t ju_128(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(128);}
static uint64_t ju_129(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(129);}
static uint64_t ju_130(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(130);}
static uint64_t ju_131(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(131);}
static uint64_t ju_132(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(132);}
static uint64_t ju_133(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(133);}
static uint64_t ju_134(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(134);}
static uint64_t ju_135(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(135);}
static uint64_t ju_136(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(136);}
static uint64_t ju_137(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(137);}
static uint64_t ju_138(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(138);}
static uint64_t ju_139(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(139);}
static uint64_t ju_140(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(140);}
static uint64_t ju_141(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(141);}
static uint64_t ju_142(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(142);}
static uint64_t ju_143(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(143);}
static uint64_t ju_144(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(144);}
static uint64_t ju_145(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(145);}
static uint64_t ju_146(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(146);}
static uint64_t ju_147(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(147);}
static uint64_t ju_148(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(148);}
static uint64_t ju_149(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(149);}
static uint64_t ju_150(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(150);}
static uint64_t ju_151(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(151);}
static uint64_t ju_152(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(152);}
static uint64_t ju_153(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(153);}
static uint64_t ju_154(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(154);}
static uint64_t ju_155(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(155);}
static uint64_t ju_156(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(156);}
static uint64_t ju_157(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(157);}
static uint64_t ju_158(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(158);}
static uint64_t ju_159(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(159);}
static uint64_t ju_160(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(160);}
static uint64_t ju_161(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(161);}
static uint64_t ju_162(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(162);}
static uint64_t ju_163(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(163);}
static uint64_t ju_164(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(164);}
static uint64_t ju_165(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(165);}
static uint64_t ju_166(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(166);}
static uint64_t ju_167(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(167);}
static uint64_t ju_168(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(168);}
static uint64_t ju_169(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(169);}
static uint64_t ju_170(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(170);}
static uint64_t ju_171(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(171);}
static uint64_t ju_172(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(172);}
static uint64_t ju_173(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(173);}
static uint64_t ju_174(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(174);}
static uint64_t ju_175(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(175);}
static uint64_t ju_176(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(176);}
static uint64_t ju_177(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(177);}
static uint64_t ju_178(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(178);}
static uint64_t ju_179(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(179);}
static uint64_t ju_180(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(180);}
static uint64_t ju_181(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(181);}
static uint64_t ju_182(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(182);}
static uint64_t ju_183(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(183);}
static uint64_t ju_184(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(184);}
static uint64_t ju_185(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(185);}
static uint64_t ju_186(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(186);}
static uint64_t ju_187(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(187);}
static uint64_t ju_188(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(188);}
static uint64_t ju_189(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(189);}
static uint64_t ju_190(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(190);}
static uint64_t ju_191(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(191);}
static uint64_t ju_192(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(192);}
static uint64_t ju_193(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(193);}
static uint64_t ju_194(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(194);}
static uint64_t ju_195(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(195);}
static uint64_t ju_196(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(196);}
static uint64_t ju_197(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(197);}
static uint64_t ju_198(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(198);}
static uint64_t ju_199(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(199);}
static uint64_t ju_200(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(200);}
static uint64_t ju_201(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(201);}
static uint64_t ju_202(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(202);}
static uint64_t ju_203(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(203);}
static uint64_t ju_204(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(204);}
static uint64_t ju_205(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(205);}
static uint64_t ju_206(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(206);}
static uint64_t ju_207(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(207);}
static uint64_t ju_208(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(208);}
static uint64_t ju_209(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(209);}
static uint64_t ju_210(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(210);}
static uint64_t ju_211(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(211);}
static uint64_t ju_212(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(212);}
static uint64_t ju_213(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(213);}
static uint64_t ju_214(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(214);}
static uint64_t ju_215(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(215);}
static uint64_t ju_216(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(216);}
static uint64_t ju_217(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(217);}
static uint64_t ju_218(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(218);}
static uint64_t ju_219(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(219);}
static uint64_t ju_220(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(220);}
static uint64_t ju_221(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(221);}
static uint64_t ju_222(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(222);}
static uint64_t ju_223(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(223);}
static uint64_t ju_224(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(224);}
static uint64_t ju_225(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(225);}
static uint64_t ju_226(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(226);}
static uint64_t ju_227(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(227);}
static uint64_t ju_228(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(228);}
static uint64_t ju_229(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(229);}
static uint64_t ju_230(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(230);}
static uint64_t ju_231(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(231);}
static uint64_t ju_232(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(232);}
static uint64_t ju_233(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(233);}
static uint64_t ju_234(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(234);}
static uint64_t ju_235(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(235);}
static uint64_t ju_236(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(236);}
static uint64_t ju_237(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(237);}
static uint64_t ju_238(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(238);}
static uint64_t ju_239(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(239);}
static uint64_t ju_240(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(240);}
static uint64_t ju_241(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(241);}
static uint64_t ju_242(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(242);}
static uint64_t ju_243(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(243);}
static uint64_t ju_244(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(244);}
static uint64_t ju_245(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(245);}
static uint64_t ju_246(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(246);}
static uint64_t ju_247(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(247);}
static uint64_t ju_248(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(248);}
static uint64_t ju_249(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(249);}
static uint64_t ju_250(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(250);}
static uint64_t ju_251(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(251);}
static uint64_t ju_252(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(252);}
static uint64_t ju_253(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(253);}
static uint64_t ju_254(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(254);}
static uint64_t ju_255(void*e,void*a,void*b,void*c,void*d,void*f,void*g){(void)e;(void)a;(void)b;(void)c;(void)d;(void)f;(void)g;return ju_log(255);}

static void *ju_slots[256] = {
  (void*)ju_0, (void*)ju_1, (void*)ju_2, (void*)ju_3, (void*)ju_4, (void*)ju_5, (void*)ju_6, (void*)ju_7,
  (void*)ju_8, (void*)ju_9, (void*)ju_10, (void*)ju_11, (void*)ju_12, (void*)ju_13, (void*)ju_14, (void*)ju_15,
  (void*)ju_16, (void*)ju_17, (void*)ju_18, (void*)ju_19, (void*)ju_20, (void*)ju_21, (void*)ju_22, (void*)ju_23,
  (void*)ju_24, (void*)ju_25, (void*)ju_26, (void*)ju_27, (void*)ju_28, (void*)ju_29, (void*)ju_30, (void*)ju_31,
  (void*)ju_32, (void*)ju_33, (void*)ju_34, (void*)ju_35, (void*)ju_36, (void*)ju_37, (void*)ju_38, (void*)ju_39,
  (void*)ju_40, (void*)ju_41, (void*)ju_42, (void*)ju_43, (void*)ju_44, (void*)ju_45, (void*)ju_46, (void*)ju_47,
  (void*)ju_48, (void*)ju_49, (void*)ju_50, (void*)ju_51, (void*)ju_52, (void*)ju_53, (void*)ju_54, (void*)ju_55,
  (void*)ju_56, (void*)ju_57, (void*)ju_58, (void*)ju_59, (void*)ju_60, (void*)ju_61, (void*)ju_62, (void*)ju_63,
  (void*)ju_64, (void*)ju_65, (void*)ju_66, (void*)ju_67, (void*)ju_68, (void*)ju_69, (void*)ju_70, (void*)ju_71,
  (void*)ju_72, (void*)ju_73, (void*)ju_74, (void*)ju_75, (void*)ju_76, (void*)ju_77, (void*)ju_78, (void*)ju_79,
  (void*)ju_80, (void*)ju_81, (void*)ju_82, (void*)ju_83, (void*)ju_84, (void*)ju_85, (void*)ju_86, (void*)ju_87,
  (void*)ju_88, (void*)ju_89, (void*)ju_90, (void*)ju_91, (void*)ju_92, (void*)ju_93, (void*)ju_94, (void*)ju_95,
  (void*)ju_96, (void*)ju_97, (void*)ju_98, (void*)ju_99, (void*)ju_100, (void*)ju_101, (void*)ju_102, (void*)ju_103,
  (void*)ju_104, (void*)ju_105, (void*)ju_106, (void*)ju_107, (void*)ju_108, (void*)ju_109, (void*)ju_110, (void*)ju_111,
  (void*)ju_112, (void*)ju_113, (void*)ju_114, (void*)ju_115, (void*)ju_116, (void*)ju_117, (void*)ju_118, (void*)ju_119,
  (void*)ju_120, (void*)ju_121, (void*)ju_122, (void*)ju_123, (void*)ju_124, (void*)ju_125, (void*)ju_126, (void*)ju_127,
  (void*)ju_128, (void*)ju_129, (void*)ju_130, (void*)ju_131, (void*)ju_132, (void*)ju_133, (void*)ju_134, (void*)ju_135,
  (void*)ju_136, (void*)ju_137, (void*)ju_138, (void*)ju_139, (void*)ju_140, (void*)ju_141, (void*)ju_142, (void*)ju_143,
  (void*)ju_144, (void*)ju_145, (void*)ju_146, (void*)ju_147, (void*)ju_148, (void*)ju_149, (void*)ju_150, (void*)ju_151,
  (void*)ju_152, (void*)ju_153, (void*)ju_154, (void*)ju_155, (void*)ju_156, (void*)ju_157, (void*)ju_158, (void*)ju_159,
  (void*)ju_160, (void*)ju_161, (void*)ju_162, (void*)ju_163, (void*)ju_164, (void*)ju_165, (void*)ju_166, (void*)ju_167,
  (void*)ju_168, (void*)ju_169, (void*)ju_170, (void*)ju_171, (void*)ju_172, (void*)ju_173, (void*)ju_174, (void*)ju_175,
  (void*)ju_176, (void*)ju_177, (void*)ju_178, (void*)ju_179, (void*)ju_180, (void*)ju_181, (void*)ju_182, (void*)ju_183,
  (void*)ju_184, (void*)ju_185, (void*)ju_186, (void*)ju_187, (void*)ju_188, (void*)ju_189, (void*)ju_190, (void*)ju_191,
  (void*)ju_192, (void*)ju_193, (void*)ju_194, (void*)ju_195, (void*)ju_196, (void*)ju_197, (void*)ju_198, (void*)ju_199,
  (void*)ju_200, (void*)ju_201, (void*)ju_202, (void*)ju_203, (void*)ju_204, (void*)ju_205, (void*)ju_206, (void*)ju_207,
  (void*)ju_208, (void*)ju_209, (void*)ju_210, (void*)ju_211, (void*)ju_212, (void*)ju_213, (void*)ju_214, (void*)ju_215,
  (void*)ju_216, (void*)ju_217, (void*)ju_218, (void*)ju_219, (void*)ju_220, (void*)ju_221, (void*)ju_222, (void*)ju_223,
  (void*)ju_224, (void*)ju_225, (void*)ju_226, (void*)ju_227, (void*)ju_228, (void*)ju_229, (void*)ju_230, (void*)ju_231,
  (void*)ju_232, (void*)ju_233, (void*)ju_234, (void*)ju_235, (void*)ju_236, (void*)ju_237, (void*)ju_238, (void*)ju_239,
  (void*)ju_240, (void*)ju_241, (void*)ju_242, (void*)ju_243, (void*)ju_244, (void*)ju_245, (void*)ju_246, (void*)ju_247,
  (void*)ju_248, (void*)ju_249, (void*)ju_250, (void*)ju_251, (void*)ju_252, (void*)ju_253, (void*)ju_254, (void*)ju_255,
};

static const char *ju_name(int slot) {
  switch (slot) {
    case 4: return "GetVersion";
    case 5: return "DefineClass";
    case 6: return "FindClass";
    case 7: return "FromReflectedMethod";
    case 8: return "FromReflectedField";
    case 9: return "ToReflectedMethod";
    case 10: return "GetSuperclass";
    case 11: return "IsAssignableFrom";
    case 12: return "ToReflectedField";
    case 13: return "Throw";
    case 14: return "ThrowNew";
    case 15: return "ExceptionOccurred";
    case 16: return "ExceptionDescribe";
    case 17: return "ExceptionClear";
    case 18: return "FatalError";
    case 19: return "PushLocalFrame";
    case 20: return "PopLocalFrame";
    case 21: return "NewGlobalRef";
    case 22: return "DeleteGlobalRef";
    case 23: return "DeleteLocalRef";
    case 24: return "IsSameObject";
    case 25: return "NewLocalRef";
    case 26: return "EnsureLocalCapacity";
    case 27: return "AllocObject";
    case 28: return "NewObject";
    case 29: return "NewObjectV";
    case 30: return "NewObjectA";
    case 31: return "GetObjectClass";
    case 32: return "IsInstanceOf";
    case 33: return "GetMethodID";
    case 63: return "CallVoidMethod";
    case 64: return "CallVoidMethodV";
    case 65: return "CallVoidMethodA";
    case 94: return "GetFieldID";
    case 95: return "GetObjectField";
    case 96: return "GetBooleanField";
    case 97: return "GetByteField";
    case 98: return "GetCharField";
    case 99: return "GetShortField";
    case 100: return "GetIntField";
    case 101: return "GetLongField";
    case 102: return "GetFloatField";
    case 103: return "GetDoubleField";
    case 104: return "SetObjectField";
    case 113: return "GetStaticMethodID";
    case 144: return "GetStaticFieldID";
    case 163: return "NewString";
    case 164: return "GetStringLength";
    case 165: return "GetStringChars";
    case 166: return "ReleaseStringChars";
    case 167: return "NewStringUTF";
    case 168: return "GetStringUTFLength";
    case 169: return "GetStringUTFChars";
    case 170: return "ReleaseStringUTFChars";
    case 171: return "GetArrayLength";
    case 172: return "NewObjectArray";
    case 173: return "GetObjectArrayElement";
    case 174: return "SetObjectArrayElement";
    case 175: return "NewBooleanArray";
    case 176: return "NewByteArray";
    case 184: return "GetBooleanArrayElements";
    case 185: return "GetByteArrayElements";
    case 199: return "ReleaseByteArrayElements";
    case 208: return "GetByteArrayRegion";
    case 215: return "SetByteArrayRegion";
    case 222: return "RegisterNatives";
    case 223: return "UnregisterNatives";
    case 224: return "MonitorEnter";
    case 225: return "MonitorExit";
    case 226: return "GetJavaVM";
    case 229: return "GetPrimitiveArrayCritical";
    case 230: return "ReleasePrimitiveArrayCritical";
    case 235: return "NewDirectByteBuffer";
    case 236: return "GetDirectBufferAddress";
    case 237: return "GetDirectBufferCapacity";
    case 238: return "GetObjectRefType";
    default: return 0;
  }
}

#endif
